### PR TITLE
WIP: updates with legacy removed and latest vtk master

### PR DESCRIPTION
**Pull request by kurtsansom**
I want to create python bindings for ACVD but first I wanted to update ACVD to the latest VTK.

The goal is not to be backwards compatible, but I suppose that would be a nice to have.

Currently I was able to get it compiling with much finagling, and warnings. However whatever I did broke the functionality. Any suggestions/Code review as I sort this out would be greatly appreciated.

### CODE REVIEW

**Comment by valette** [comment]
Hi, thank you for this! Unfortunately, cmake fails on my machine:
```
[valette@desk ACVD]$ cmake .
CMake Error at /usr/lib64/cmake/vtk/vtkModuleAPI.cmake:143 (message):
  Requested modules not available:

    CommonCore
    CommonDataModel
    RenderingCore
    CommonSystem
    IOImport
    IOExport
    IOImage
    IOGeometry
    IOPLY
    FiltersSources
    InteractionStyle
    FiltersHybrid
    RenderingLabel
    IOMINC
    FiltersModeling
    FiltersGeneral
    metaio
    ImagingGeneral
Call Stack (most recent call first):
  /usr/lib64/cmake/vtk/VTKConfig.cmake:140 (vtk_module_config)
  CMakeLists.txt:34 (find_package)
```
which version of VTK are you aiming at?

**Comment by kurtsansom** [comment]
I am currently building against vtk master (which should be close enough to vtk 9.0) I think they are on release candidate 3. vtk 9.0

I think you can prepend each module with vtk and it should work with vtk 8.

**Comment by valette** [comment]
Hello, thank you for your efforts! I have created a branch for vtk9 [/valette/ACVD/tree/vtk9](/valette/ACVD/tree/vtk9)  , which I aim to be fully retro-compatible in the future, but for now it is dedicated to vtk9.
I wanted to keep the API mostly unchanged so I had to cook ly own vtkSurface::GetFaceVertices() methods.
I did not pull our code, but if you can propose modifications to the vtk9 branch , it would be great (especially the CMake stuff, but on my box it compiles without modifications to the original code)

This is very fresh code, tested only on a few cases with ACVD, ACVDQ and AnisotropicRemeshingQ
Thank you again,
Sebastien

**Comment by valette** [comment]
Okay I've pushed my update to the master tree, should be fully working!

**Pull request closed without merging**
